### ISSUE TITLE
Create Assets

### ISSUE THREAD

**Issue by GDWR** [SavagePastaMan/pyweek-2021#2]
32 x 32 px 

* Walls (all direction)
* Flooring 
* Escapee
* Cop
* Key (UI Element)
* Cabinet / Key Safe / Locker
* Other Things you find in jail (for decoration)

**Comment by SavagePastaMan** [comment]
We also need assets for a main menu

**Comment by GDWR** [comment]
> 
> 
> We also need assets for a main menu

Can you make a list or something with general ideas of what and why.
