### ISSUE TITLE
Audio Controller

### ISSUE THREAD

**Issue by GDWR** [SavagePastaMan/pyweek-2021#26]
We need a game wide controller that will sit on the GameView.
This should ensure that only one soundtrack is played at a time. 

Should have methods to switch, restart or pause tracks etc.
Arcade might have a builtin for all this stuff.

**Comment by SavagePastaMan** [comment]
arcade does have many of this built-in. i'm a bit apprehensive about letting the user switch between tracks, since that would require us to create a menu for that. it should be firmly under the control of the game

**Comment by GDWR** [comment]
I agree, the methods I have mentioned would be used by objects etc. Inside the main loop as to stop multiple audio files from playing at once. It shouldn't be exposed to the player imo

**Comment by SavagePastaMan** [comment]
we should play sound effects on top of the background music, that shouldn't be a problem

**Comment by SavagePastaMan** [comment]
forgot to link this loops, related pr has been merged
