### ISSUE TITLE
Enemy Movement work in progress

### ISSUE THREAD

**Issue by anythingapplied** [SavagePastaMan/pyweek-2021#27]
Commit message for 1c1d622f5c2789b1de76d85344a867028d7a9214 mentioned a number of open issues with enemy movements:

Issues:

- [X] Paths are drawn at top left corner instead of center
- [x] Paths should be different colors for each guard
- [x] Paths are sometimes returning None, presumably because no path was found, even when there should've been
- [x] Need to put in correct numbers for the edge of the board as required by the A* algorithm
- [ ] Need to implement guard turning and direction facing
- [x] With A*, guards take a slightly different path back, maybe not the best choice. Unable to distinguish forward path from backward path so breaks predictability for the player

**Comment by GDWR** [comment]
Duplicate of #19 

Looks good tho!

**Comment by anythingapplied** [comment]
Direction facing moved to #20.

Color paths moved to its own issue, because we eventually have to address when we need more than 6 guards.
