### ISSUE TITLE
scaling issues

### ISSUE THREAD

**Issue by SavagePastaMan** [SavagePastaMan/pyweek-2021#57]
this is likely due to the change in tile size between test level and our new tileset

**Comment by SavagePastaMan** [comment]
assigning you since you wrote this code

**Comment by SavagePastaMan** [comment]
from my testing, it seems there is an issue with the mapping between coordinates on the map, and coordinates on the window. from what i can gather this seems to be some constant value that i can't determine. i'm not familiar with any of this code, so you're the best person for it :3

**Comment by anythingapplied** [comment]
I adjusted the scaling factors to match the new tileset.  See c862f46dd66ecb61ab30e310117509cfc98195f0
