### ISSUE TITLE
UI Elements

### ISSUE THREAD

**Issue by anythingapplied** [SavagePastaMan/pyweek-2021#6]
Possibly needed UI Elements:

- [x] Main Menu page
- [x] Credits page (Reminder to include attribution for any game assets we downloaded from other sources)
- [ ] Help page - Explains all items, units, and cell types
- [x] Settings page - mute audio
- [ ] Level intro to explain newly introduced elements
- [x] Game pause menu
- [ ] Level selection menu
- [ ] Create custom generated game menu

**Comment by GDWR** [comment]
@anythingapplied will this be extended into creating in-game UI for keys etc.? Or should I make a new branch for them UI elements?

**Comment by SavagePastaMan** [comment]
those should be created in the gameview, so a different branch

**Comment by SavagePastaMan** [comment]
Additional elements not named, but will be added

- [ ] "Game lost page", for being caught by a cop
- [ ] "Game won page" for beating the game
